title: Aishwarya Naik  
description: >  
  Data Scientist | Machine Learning Enthusiast | AI Researcher  
  Passionate about leveraging data to drive insights and innovation.  

show_downloads: true  
theme: jekyll-theme-minimal  

# Profile photo  
avatar: https://github.com/naikaishwarya23/portfolio/blob/main/1000139026.png

# Navigation links  
navigation:  
  - title: About Me  
    url: /about  
  - title: Projects  
    url: /projects  
  - title: Blog  
    url: /blog  
  - title: Contact  
    url: /contact  

# Personal interests  
personal_interests:  
  - Machine Learning  
  - Deep Learning  
  - Natural Language Processing  
  - Data Visualization  
  - AI Ethics  
  - Open-Source Contributions  

# Featured Projects  
projects:  
  - title: Skill Wiser  
    description: Extracts and clusters job skills from job descriptions using NLP and ML techniques.  
    url: https://github.com/naikaishwarya23/SkillWiser
  - title: Spending Habits Unveiled 
    description: Analysis of individuals' spending habits based on various demographic and lifestyle factors. 
    url: https://github.com/naikaishwarya23/SpendingHabitsUnveiled
  - title: Human Activity Recognition   
    description: Predicts human activity recognition using smartphone sensor data. 
    url: https://github.com/naikaishwarya23/HumanActivityRecognition 

# Social links  
social:  
  github: https://github.com/naikaishwarya23  
  linkedin: https://www.linkedin.com/in/naikaishwarya   

# Build settings  
plugins:  
  - jekyll-seo-tag  
  - jekyll-sitemap  
